# Importing all the modules required.
import turtle
import time
from snake import Snake
from food import Food
from score import Score

screen = turtle.Screen()
def set_screen():
    """Setting the screen / canvas for the game"""
    screen.setup(width = 600, height = 600) # Setting the screen of dimensions 600 x 600.
    screen.listen() # Letting the screen listen onclick events generated by the player.
    screen.bgcolor("Black") # Setting the background colour of the screen to black.
    screen.bgpic("green_field.png") # Creating a field image for the snake.
    screen.title("Apple Snake")
    screen.tracer(0) # turning tracer method off (i.e. setting it 0). Turn turtle(snake_body) animation off.

def SnakeGame():
    """This is the function of main snake game. It can be recursive based on play again or not."""
    screen.resetscreen()
    set_screen()
    snake = Snake()
    food = Food()
    score = Score()

    # actions to be performed after the responses taken from the user through keyboard.
    screen.onkey(key="Up", fun=snake.move_up)
    screen.onkey(key="Down", fun=snake.move_down)
    screen.onkey(key="Right", fun=snake.move_right)
    screen.onkey(key="Left", fun=snake.move_left)

    game = True
    while game:
        screen.update() # updating the screen only after my snake moves (i.e. not showing the single body of snake moving)
        time.sleep(0.1) # Adding Delay so I can see the snake moving.
        snake.move() # Continuously moving the snake.

        # Detect collision with food.
        if snake.snake_head.distance(food) < 15:
            food.refresh()
            snake.extend()
            score.increase_score()

        # Detect collision with wall.
        if snake.snake_head.xcor() > 280 or snake.snake_head.xcor() < -280 or snake.snake_head.ycor() > 260 or snake.snake_head.ycor() < -280:
            score.game_over()
            # if you make a replay option and the return value of game over is true then call the SnakeGame() function otherwise game = false.
            game = False

        # Detect collision with body.
        for body in snake.snake[1:]:
            if snake.snake_head.distance(body) < 10:
                score.game_over()
                # if you make a replay option and the return value of game over is true then call the SnakeGame() function otherwise game = false.
                game = False
SnakeGame()

screen.exitonclick()
